#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Build Hi-C paired datasets with downsampled counts (same resolution).

- Both HR and LR tiles: 512x512 @ 25 kb
- LR generated by stochastic downsampling of counts
- Preprocessing pipeline (per window):
    Balanced counts (unless --no-balance)
    -> O/E by genomic distance stratum (expected = mean within the window)
    -> asinh stabilization
    -> per-stratum z-score (μ,σ computed within the same window & stratum)

Outputs:
    highdepth_dataset.npy   (N,1,512,512)   preprocessed HR
    lowdepth_dataset.npy    (N,1,512,512)   preprocessed LR
    highdepth_mask.npy      (N,1,512,512)
    lowdepth_mask.npy       (N,1,512,512)
    hic_window_coords.npy   (N,) object of (chrom, start_bp, end_bp)
"""

import os
import argparse
import numpy as np
import cooler


# ---------- helpers: downsampling ----------

def downsample_counts(M: np.ndarray, frac: float, rng: np.random.Generator) -> np.ndarray:
    """Stochastic thinning of counts to simulate fewer reads.
    Safely clips negatives before binomial thinning.
    """
    M_nonneg = np.clip(M, 0, None).astype(np.int64, copy=False)
    if frac <= 0:
        return np.zeros_like(M, dtype=np.float32)
    if frac >= 1:
        return M_nonneg.astype(np.float32)
    return rng.binomial(M_nonneg, frac).astype(np.float32)


# ---------- helpers: window-level O/E → asinh → per-stratum z-score ----------

def _stratum_indices(n: int, k: int):
    """Return index pairs for the diagonals where |i-j| == k (upper and lower)."""
    r = np.arange(n - k)
    c = r + k
    # upper triangle indices (i, j) with j = i + k
    upper = (r, c)
    if k == 0:
        return [upper]
    # symmetric lower triangle indices (j, i)
    lower = (c, r)
    return [upper, lower]


def oe_asinh_stratum_zscore_tile(H: np.ndarray, Hm: np.ndarray, eps: float = 1e-6) -> np.ndarray:
    """
    Per-window pipeline:
      1) Expected-by-stratum within this window (mean of valid cells per |i-j|=k).
      2) O/E = H / expected[k]  (guarded by eps).
      3) asinh stabilization.
      4) Per-stratum z-score within this window (μ_k, σ_k from valid cells).

    Invalid cells (mask==0) are left as 0 in the output.
    """
    H = H.astype(np.float32, copy=False)
    Hm = (Hm.astype(np.float32, copy=False) > 0).astype(np.float32)
    n = H.shape[0]

    # 1) expected per stratum
    expected = np.zeros(n, dtype=np.float32)
    for k in range(n):
        vals = []
        for (rr, cc) in _stratum_indices(n, k):
            mvalid = Hm[rr, cc] > 0
            if mvalid.any():
                vals.append(H[rr, cc][mvalid])
        if vals:
            expected[k] = float(np.mean(np.concatenate(vals)))
        else:
            expected[k] = 0.0

    # 2) O/E per stratum
    OE = np.zeros_like(H, dtype=np.float32)
    for k in range(n):
        denom = expected[k] if expected[k] > eps else 1.0  # avoid tiny/zero expected
        for (rr, cc) in _stratum_indices(n, k):
            OE[rr, cc] = H[rr, cc] / denom

    # 3) asinh
    T = np.arcsinh(OE).astype(np.float32)

    # 4) per-stratum z-score within this window
    Z = np.zeros_like(T, dtype=np.float32)
    for k in range(n):
        vals = []
        idxs = []
        for (rr, cc) in _stratum_indices(n, k):
            mvalid = (Hm[rr, cc] > 0)
            if mvalid.any():
                vals.append(T[rr, cc][mvalid])
                idxs.append((rr[mvalid], cc[mvalid]))
        if not vals:
            continue
        cat = np.concatenate(vals)
        mu = float(cat.mean())
        sd = float(cat.std(ddof=0))
        if sd < eps:
            for (rrv, ccv) in idxs:
                Z[rrv, ccv] = T[rrv, ccv] - mu
        else:
            for (rrv, ccv) in idxs:
                Z[rrv, ccv] = (T[rrv, ccv] - mu) / sd

    # zero out invalids; let mask guide the model
    Z[Hm == 0] = 0.0
    return Z


def preprocess_counts_batch_oe_asinh_stratz(X: np.ndarray, masks: np.ndarray) -> np.ndarray:
    """Batch apply oe_asinh_stratum_zscore_tile for (N, H, W) arrays with masks."""
    assert X.shape == masks.shape, "Counts and mask shapes must match"
    N = X.shape[0]
    out = np.empty_like(X, dtype=np.float32)
    for i in range(N):
        out[i] = oe_asinh_stratum_zscore_tile(X[i], masks[i])
    return out


# ---------- extraction ----------

def extract_hr_windows(data_folder,
                       highres_res,
                       high_bins,
                       stride_bins,
                       min_valid_frac,
                       skip_chrY,
                       balanced=True):
    hi_tiles, hi_masks, coords = [], [], []
    mcools = [f for f in sorted(os.listdir(data_folder)) if f.endswith(".mcool")]
    if not mcools:
        raise FileNotFoundError(f"No .mcool files in {data_folder}")

    for fname in mcools:
        path = os.path.join(data_folder, f"{fname}::resolutions/{highres_res}")
        print(f"\n>>> {fname} @ {highres_res}")
        clr = cooler.Cooler(path)

        for chrom in clr.chromnames:
            if skip_chrY and chrom.lower().endswith("y"):
                continue

            # load counts (balanced or not)
            M = clr.matrix(balance=balanced).fetch(chrom).astype(np.float32)
            mask = np.isfinite(M).astype(np.float32)
            M = np.nan_to_num(M, nan=0.0)

            kept = 0
            for j in range(0, M.shape[0] - high_bins + 1, stride_bins):
                start_bp = j * highres_res
                end_bp   = start_bp + high_bins * highres_res
                H  = M[j:j+high_bins, j:j+high_bins]
                Hm = mask[j:j+high_bins, j:j+high_bins]

                if Hm.mean() < min_valid_frac:
                    continue

                hi_tiles.append(H)
                hi_masks.append(Hm)
                coords.append((chrom, int(start_bp), int(end_bp)))
                kept += 1
            print(f"  {chrom}: kept {kept} windows")

    hi_tiles = np.stack(hi_tiles).astype(np.float32)
    hi_masks = np.stack(hi_masks).astype(np.float32)
    coords   = np.array(coords, dtype=object)
    print("\n--- extracted ---")
    print("hi_tiles:", hi_tiles.shape)
    return hi_tiles, hi_masks, coords


# ---------- main ----------

def main():
    ap = argparse.ArgumentParser(description="Build Hi-C dataset with downsampled reads")
    ap.add_argument("--data-folder", type=str, required=True)
    ap.add_argument("--highres-res", type=int, default=25_000)
    ap.add_argument("--high-bins", type=int, default=512)
    ap.add_argument("--stride-bins", type=int, default=256)
    ap.add_argument("--min-valid-frac", type=float, default=0.70)
    ap.add_argument("--skip-chrY", action="store_true", default=True)
    ap.add_argument("--no-balance", action="store_true",
                    help="If set, use raw unbalanced counts from .mcool")
    ap.add_argument("--downsample-frac", type=float, default=0.25,
                    help="Fraction of reads kept for low-depth (e.g., 0.25=25%)")
    ap.add_argument("--out-prefix", type=str, default="")
    args = ap.parse_args()

    hi_counts, hi_mask, coords = extract_hr_windows(
        data_folder=args.data_folder,
        highres_res=args.highres_res,
        high_bins=args.high_bins,
        stride_bins=args.stride_bins,
        min_valid_frac=args.min_valid_frac,
        skip_chrY=args.skip_chrY,
        balanced=not args.no_balance,
    )
    N = hi_counts.shape[0]

    rng = np.random.default_rng(42)

    # Low-depth via stochastic thinning (on nonnegative integerized counts)
    lo_counts = np.stack([
        downsample_counts(hi_counts[i], args.downsample_frac, rng)
        for i in range(N)
    ]).astype(np.float32)
    lo_mask = hi_mask.copy()  # masks unchanged

    print("\n--- downsampled -> LR ---")
    print("lo_counts:", lo_counts.shape)

    # Preprocess both:
    # Balanced -> O/E(by stratum, per window) -> asinh -> per-stratum z-score
    print("\n--- preprocessing HR ---")
    hi_img = preprocess_counts_batch_oe_asinh_stratz(hi_counts, hi_mask)

    print("\n--- preprocessing LR ---")
    lo_img = preprocess_counts_batch_oe_asinh_stratz(lo_counts, lo_mask)

    # Package (add channel dim)
    highres_img  = hi_img[:, None]
    highres_mask = hi_mask[:, None]
    lowres_img   = lo_img[:, None]
    lowres_mask  = lo_mask[:, None]

    # Save
    def _name(x): return f"{args.out_prefix}{x}" if args.out_prefix else x
    np.save(_name("highdepth_dataset.npy"), highres_img)
    np.save(_name("highdepth_mask.npy"),    highres_mask)
    np.save(_name("lowdepth_dataset.npy"),  lowres_img)
    np.save(_name("lowdepth_mask.npy"),     lowres_mask)
    np.save(_name("hic_window_coords.npy"), coords)

    print("\n--- final tensors ---")
    print("highdepth_dataset:", highres_img.shape)
    print("lowdepth_dataset :", lowres_img.shape)
    print(f"Saved {N} datapoints ✓")


if __name__ == "__main__":
    main()